title: "kavyashree2001"
email: ukkkavyashree2001@gmail.com
description: a sophomore fascinated towards open source contribution.
baseurl: "/" 
url: "https://kavyashree2001.github.io/" 
twitter_username: 
github_username:  kavyashree2001

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
